"""
Phase 9: Qwen 2.5 LoRA Fine-Tuning Pipeline (09_train_qwen.py)
Fine-tunes Qwen/Qwen2.5-0.5B-Instruct on CHARM XAI explainability data.
Outputs a lightweight LoRA adapter (~25MB) saved to models/qwen_xai_adapter.
"""

import os
import sys
import json
import torch

current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)
from typing import List, Dict, Any
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq
)
from peft import LoraConfig, get_peft_model, TaskType, PeftModel

# Bypass PEFT torchao version check bug in Python 3.13 / Colab
try:
    import peft.import_utils
    peft.import_utils.is_torchao_available = lambda: False
    import peft.tuners.lora.torchao
    peft.tuners.lora.torchao.is_torchao_available = lambda: False
except Exception:
    pass

BASE_DIR = "/content/drive/MyDrive/Capstone_Project" if os.path.exists("/content/drive") else "."
MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"
DATASET_PATH = os.path.join(BASE_DIR, "datasets", "translation_training_data.jsonl")
OUTPUT_DIR = os.path.join(BASE_DIR, "models", "qwen_xai_adapter")

def load_and_preprocess_dataset(tokenizer, data_path: str = DATASET_PATH) -> Dataset:
    """Loads JSONL dataset and formats using Qwen's official chat template."""
    if not os.path.exists(data_path):
        raise FileNotFoundError(f"Training dataset not found at {data_path}. Run 08_generate_qwen_training_dataset.py first.")

    raw_data = []
    with open(data_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                raw_data.append(json.loads(line.strip()))

    print(f"[-] Loaded {len(raw_data)} samples from {data_path}")

    formatted_samples = []
    for item in raw_data:
        messages = item["messages"]
        # Apply Qwen chat template to convert messages to tokenized sequence
        text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
        formatted_samples.append({"text": text})

    dataset = Dataset.from_list(formatted_samples)

    def tokenize_fn(examples):
        tokens = tokenizer(
            examples["text"],
            max_length=512,
            truncation=True,
        )
        tokens["labels"] = [list(seq) for seq in tokens["input_ids"]]
        return tokens

    tokenized_dataset = dataset.map(tokenize_fn, batched=True, remove_columns=["text"])
    return tokenized_dataset

def train(
    base_model_name: str = MODEL_NAME,
    dataset_path: str = DATASET_PATH,
    output_dir: str = OUTPUT_DIR,
    epochs: int = 3,
    batch_size: int = 4,
    gradient_accumulation_steps: int = 2,
    learning_rate: float = 2e-4
):
    """Executes LoRA fine-tuning for Qwen 2.5 on CHARM explainability."""
    device = "cuda" if torch.cuda.is_available() else "cpu"
    dtype = torch.float16 if device == "cuda" else torch.float32
    print(f"[-] Target Training Hardware: {device.upper()}")
    if device == "cuda":
        print(f"    [+] GPU: {torch.cuda.get_device_name(0)} ({torch.cuda.get_device_properties(0).total_memory / (1024**3):.2f} GB VRAM)")

    print(f"[-] Loading Base Tokenizer ({base_model_name})...")
    tokenizer = AutoTokenizer.from_pretrained(base_model_name, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Check for dedicated train/val partitions generated by 08_generate_translation_dataset.py
    train_split_path = os.path.join(os.path.dirname(dataset_path), "qwen_xai_train.jsonl")
    val_split_path = os.path.join(os.path.dirname(dataset_path), "qwen_xai_val.jsonl")

    if os.path.exists(train_split_path) and os.path.exists(val_split_path):
        print(f"[-] Loading dedicated pre-partitioned train & validation files...")
        print(f"    [+] Train source: {train_split_path}")
        print(f"    [+] Val source:   {val_split_path}")
        train_dataset = load_and_preprocess_dataset(tokenizer, train_split_path)
        eval_dataset = load_and_preprocess_dataset(tokenizer, val_split_path)
    else:
        print(f"[-] Preprocessing dataset from {dataset_path}...")
        dataset = load_and_preprocess_dataset(tokenizer, dataset_path)
        split_dataset = dataset.train_test_split(test_size=0.1, seed=42)
        train_dataset = split_dataset["train"]
        eval_dataset = split_dataset["test"]

    print(f"    [+] Train samples: {len(train_dataset)}, Eval samples: {len(eval_dataset)}")

    # Configure 4-bit NF4 Quantization (QLoRA) with graceful fallback
    bnb_config = None
    if device == "cuda":
        try:
            from transformers import BitsAndBytesConfig
            from peft import prepare_model_for_kbit_training
            bnb_config = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_compute_dtype=torch.float16,
                bnb_4bit_use_double_quant=True
            )
            print("    [+] Activated 4-bit NF4 Quantization (QLoRA) via bitsandbytes.")
        except Exception as q_err:
            print(f"    [!] bitsandbytes quantization unavailable ({q_err}); using standard precision.")
            bnb_config = None

    if bnb_config is not None:
        model = AutoModelForCausalLM.from_pretrained(
            base_model_name,
            quantization_config=bnb_config,
            device_map="auto"
        )
        model = prepare_model_for_kbit_training(model)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            base_model_name,
            torch_dtype=dtype,
            device_map="auto" if device == "cuda" else None
        )

    # Configure Parameter-Efficient Fine-Tuning (LoRA)
    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type=TaskType.CAUSAL_LM
    )

    model = get_peft_model(model, lora_config)
    trainable_params, all_params = model.get_nb_trainable_parameters()
    print(f"    [+] Trainable LoRA Params: {trainable_params:,} / {all_params:,} ({100 * trainable_params / all_params:.2f}%)")

    os.makedirs(output_dir, exist_ok=True)
    eval_arg = "eval_strategy" if hasattr(TrainingArguments, "eval_strategy") else "evaluation_strategy"
    training_args = TrainingArguments(
        output_dir=os.path.join(output_dir, "checkpoints"),
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        learning_rate=learning_rate,
        weight_decay=0.01,
        warmup_steps=20,
        logging_steps=10,
        save_strategy="epoch",
        save_total_limit=1,
        fp16=(dtype == torch.float16 or (bnb_config is not None)),
        bf16=(dtype == torch.bfloat16),
        report_to="none",
        **{eval_arg: "epoch"}
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        data_collator=DataCollatorForSeq2Seq(tokenizer, pad_to_multiple_of=8, return_tensors="pt")
    )

    print("[-] Commencing Training...")
    trainer.train()

    print(f"[-] Saving Trained LoRA Adapter to {output_dir}...")
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"[+] Model Adapter successfully saved to {output_dir}")

def test_inference(adapter_dir: str = OUTPUT_DIR):
    """Smoke tests the trained LoRA adapter with live telemetry."""
    print("[-] Running Sample Inference on Trained Adapter...")
    device = "cuda" if torch.cuda.is_available() else "cpu"
    tokenizer = AutoTokenizer.from_pretrained(adapter_dir)
    dtype = torch.float16 if torch.cuda.is_available() else torch.float32
    
    base_model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype=dtype,
        device_map="auto" if device == "cuda" else None
    )
    model = PeftModel.from_pretrained(base_model, adapter_dir)
    model.eval()

    test_messages = [
        {"role": "system", "content": "You are an AI Reliability Explainability Assistant conforming to NIST AI 600-1. Respond ONLY with valid JSON."},
        {"role": "user", "content": (
            "Stage Number: Step 2 (Executed by: OrchestratorAgent)\n"
            "Detected Cascade Pattern: Inference Cascade\n"
            "Combined Anomaly Score: 0.82 (Threshold: 0.55)\n"
            "Factual Verification Deficit (SFV): 0.85\n"
            "Cross-Stage Drift Score (CSCT): 0.65\n"
            "Prescribed Technical Remedy: PVA\n"
            "Preceding Step Context: \"IT Policy 3.2: Computer displays up to $300 once every 24 months.\"\n"
            "Current Step Output: \"Reasoning: Employees can purchase ultra-wide monitors up to $3,000 every year.\""
        )}
    ]

    prompt = tokenizer.apply_chat_template(test_messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=256,
            temperature=0.1,
            do_sample=False
        )

    response_text = tokenizer.decode(outputs[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
    print(f"\n[+] Generated XAI Output:\n{response_text}")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--test-only", action="store_true", help="Run test inference on existing weights")
    args = parser.parse_args()

    if args.test_only:
        test_inference()
    else:
        # 1. Generate dataset if missing
        if not os.path.exists(DATASET_PATH):
            import importlib
            gen_module = importlib.import_module("08_generate_qwen_training_dataset")
            gen_module.build_dataset(num_samples_per_mode=75, output_dir=os.path.dirname(DATASET_PATH))

        # 2. Run training
        train()
        # 3. Test verification
        test_inference()
